
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "VultEngine.h"

void Util__ctx_type_1_init(Util__ctx_type_1 &_output_){
   Util__ctx_type_1 _ctx;
   _ctx.pre = 0;
   _output_ = _ctx;
   return ;
}

void Util_edge_init(Util__ctx_type_1 &_output_){
   Util__ctx_type_1_init(_output_);
   return ;
}

uint8_t Util_edge(Util__ctx_type_1 &_ctx, uint8_t x){
   uint8_t ret;
   ret = (x && bool_not(_ctx.pre));
   _ctx.pre = x;
   return ret;
}

void Util__ctx_type_2_init(Util__ctx_type_2 &_output_){
   Util__ctx_type_2 _ctx;
   _ctx.pre_x = 0.f;
   _output_ = _ctx;
   return ;
}

void Util_change_init(Util__ctx_type_2 &_output_){
   Util__ctx_type_2_init(_output_);
   return ;
}

uint8_t Util_change(Util__ctx_type_2 &_ctx, float x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

float Util_cubic_clipper(float x){
   uint8_t _cond_27;
   _cond_27 = (x <= -0.666666666667f);
   if(_cond_27){
      return -0.666666666667f;
   }
   else
   {
      uint8_t _cond_26;
      _cond_26 = (x >= 0.666666666667f);
      if(_cond_26){
         return 0.666666666667f;
      }
      else
      {
         return (x + (-0.333333333333f * x * x * x));
      }
   }
}

float Util_stanh(float x){
   int index;
   index = int_clip(float_to_int((5.f * (x + 24.f))),0,240);
   return (float_wrap_array(Util_stanh_c0)[index] + (x * (float_wrap_array(Util_stanh_c1)[index] + (float_wrap_array(Util_stanh_c2)[index] * x))));
}

float Util_sine(float x){
   int index;
   index = int_clip(float_to_int((100.f * x)),0,100);
   return (float_wrap_array(Util_sine_c0)[index] + (x * (float_wrap_array(Util_sine_c1)[index] + (float_wrap_array(Util_sine_c2)[index] * x))));
}

float Util_saturate(float x){
   int index;
   index = int_clip(float_to_int((5.f * (x + 24.f))),0,240);
   return (float_wrap_array(Util_saturate_c0)[index] + (x * (float_wrap_array(Util_saturate_c1)[index] + (float_wrap_array(Util_saturate_c2)[index] * x))));
}

float Util_map(float x, float x0, float x1, float y0, float y1){
   return ((((x + (- x0)) * (y1 + (- y0))) / (x1 + (- x0))) + y0);
}

void Util__ctx_type_8_init(Util__ctx_type_8 &_output_){
   Util__ctx_type_8 _ctx;
   _ctx.y1 = 0.f;
   _ctx.x1 = 0.f;
   _output_ = _ctx;
   return ;
}

void Util_dcblock_init(Util__ctx_type_8 &_output_){
   Util__ctx_type_8_init(_output_);
   return ;
}

float Util_dcblock(Util__ctx_type_8 &_ctx, float x0){
   float y0;
   y0 = (x0 + (- _ctx.x1) + (_ctx.y1 * 0.995f));
   _ctx.x1 = x0;
   _ctx.y1 = y0;
   return y0;
}

void Util__ctx_type_9_init(Util__ctx_type_9 &_output_){
   Util__ctx_type_9 _ctx;
   _ctx.x = 0.f;
   _output_ = _ctx;
   return ;
}

void Util_smooth_init(Util__ctx_type_9 &_output_){
   Util__ctx_type_9_init(_output_);
   return ;
}

float Util_smooth(Util__ctx_type_9 &_ctx, float input){
   _ctx.x = (_ctx.x + ((input + (- _ctx.x)) * 0.005f));
   return _ctx.x;
}

float Util_cvToPitch(float cv){
   return ((cv * 120.f) + 24.f);
}

float Util_cvToperiodUnit(float cv){
   int index;
   index = int_clip(float_to_int((31.f * cv)),0,31);
   return (float_wrap_array(Util_cvToperiodUnit_c0)[index] + (cv * (float_wrap_array(Util_cvToperiodUnit_c1)[index] + (float_wrap_array(Util_cvToperiodUnit_c2)[index] * cv))));
}

float Util_cvTokHz(float cv){
   int index;
   index = int_clip(float_to_int((31.f * cv)),0,31);
   return (float_wrap_array(Util_cvTokHz_c0)[index] + (cv * (float_wrap_array(Util_cvTokHz_c1)[index] + (float_wrap_array(Util_cvTokHz_c2)[index] * cv))));
}

float Util_pitchToRateUnit(float pitch){
   int index;
   index = int_clip(float_to_int((0.244094488189f * pitch)),0,31);
   return (float_wrap_array(Util_pitchToRateUnit_c0)[index] + (pitch * (float_wrap_array(Util_pitchToRateUnit_c1)[index] + (float_wrap_array(Util_pitchToRateUnit_c2)[index] * pitch))));
}

float Util_cvToRateUnit(float cv){
   int index;
   index = int_clip(float_to_int((141.111111111f * cv)),0,127);
   return (float_wrap_array(Util_cvToRateUnit_c0)[index] + (cv * (float_wrap_array(Util_cvToRateUnit_c1)[index] + (float_wrap_array(Util_cvToRateUnit_c2)[index] * cv))));
}

void Util__ctx_type_15_init(Util__ctx_type_15 &_output_){
   Util__ctx_type_15 _ctx;
   _ctx.rate = 0.f;
   Util__ctx_type_2_init(_ctx._inst20);
   Util__ctx_type_2_init(_ctx._inst19);
   _output_ = _ctx;
   return ;
}

void Util_pitchToRate_init(Util__ctx_type_15 &_output_){
   Util__ctx_type_15_init(_output_);
   return ;
}

float Util_pitchToRate(Util__ctx_type_15 &_ctx, float pitch){
   float fs;
   fs = getSampleRate();
   uint8_t _cond_29;
   _cond_29 = (Util_change(_ctx._inst19,pitch) || Util_change(_ctx._inst20,fs));
   if(_cond_29){
      _ctx.rate = (Util_pitchToRateUnit(pitch) / getSampleRate());
   }
   return _ctx.rate;
}

void Util__ctx_type_16_init(Util__ctx_type_16 &_output_){
   Util__ctx_type_16 _ctx;
   _ctx.rate = 0.f;
   Util__ctx_type_2_init(_ctx._inst24);
   Util__ctx_type_2_init(_ctx._inst23);
   _output_ = _ctx;
   return ;
}

void Util_cvToRate_init(Util__ctx_type_16 &_output_){
   Util__ctx_type_16_init(_output_);
   return ;
}

float Util_cvToRate(Util__ctx_type_16 &_ctx, float cv){
   float fs;
   fs = getSampleRate();
   uint8_t _cond_30;
   _cond_30 = (Util_change(_ctx._inst23,cv) || Util_change(_ctx._inst24,fs));
   if(_cond_30){
      _ctx.rate = (Util_cvToRateUnit(cv) / fs);
   }
   return _ctx.rate;
}

float Stabile_calc_g(float cv, float fs){
   float pitch;
   pitch = Util_cvToPitch(cv);
   float f;
   f = (8.17579891564f * expf((0.0577622650467f * pitch)));
   float wd;
   wd = (6.28318530718f * f);
   float T;
   T = (1.f / fs);
   float wa;
   wa = ((2.f / T) * tanf((wd * T * 0.5f)));
   float g;
   g = (wa * T * 0.5f);
   return g;
}

float Stabile_calc_g_44100(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_44100_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_44100_c1)[index] + (float_wrap_array(Stabile_calc_g_44100_c2)[index] * cv))));
}

float Stabile_calc_g_48000(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_48000_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_48000_c1)[index] + (float_wrap_array(Stabile_calc_g_48000_c2)[index] * cv))));
}

float Stabile_calc_g_88200(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_88200_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_88200_c1)[index] + (float_wrap_array(Stabile_calc_g_88200_c2)[index] * cv))));
}

float Stabile_calc_g_96000(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_96000_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_96000_c1)[index] + (float_wrap_array(Stabile_calc_g_96000_c2)[index] * cv))));
}

float Stabile_calc_g_176400(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_176400_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_176400_c1)[index] + (float_wrap_array(Stabile_calc_g_176400_c2)[index] * cv))));
}

float Stabile_calc_g_192000(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Stabile_calc_g_192000_c0)[index] + (cv * (float_wrap_array(Stabile_calc_g_192000_c1)[index] + (float_wrap_array(Stabile_calc_g_192000_c2)[index] * cv))));
}

float Stabile_tune(float cv){
   float fs;
   fs = getSampleRate();
   float g;
   g = 0.f;
   uint8_t _cond_61;
   _cond_61 = (fs == 44100.f);
   if(_cond_61){
      g = Stabile_calc_g_44100(cv);
   }
   else
   {
      uint8_t _cond_60;
      _cond_60 = (fs == 48000.f);
      if(_cond_60){
         g = Stabile_calc_g_48000(cv);
      }
      else
      {
         uint8_t _cond_59;
         _cond_59 = (fs == 88200.f);
         if(_cond_59){
            g = Stabile_calc_g_88200(cv);
         }
         else
         {
            uint8_t _cond_58;
            _cond_58 = (fs == 96000.f);
            if(_cond_58){
               g = Stabile_calc_g_96000(cv);
            }
            else
            {
               uint8_t _cond_57;
               _cond_57 = (fs == 176400.f);
               if(_cond_57){
                  g = Stabile_calc_g_176400(cv);
               }
               else
               {
                  uint8_t _cond_56;
                  _cond_56 = (fs == 192000.f);
                  if(_cond_56){
                     g = Stabile_calc_g_192000(cv);
                  }
                  else
                  {
                     g = Stabile_calc_g(cv,getSampleRate());
                  }
               }
            }
         }
      }
   }
   return g;
}

void Stabile__ctx_type_8_init(Stabile__ctx_type_8 &_output_){
   Stabile__ctx_type_8 _ctx;
   _ctx.z2 = 0.f;
   _ctx.z1 = 0.f;
   _ctx.inv_den = 0.f;
   _ctx.g = 0.f;
   Util__ctx_type_2_init(_ctx._inst53);
   Util__ctx_type_2_init(_ctx._inst52);
   _ctx.R = 0.f;
   Stabile_default(_ctx);
   _output_ = _ctx;
   return ;
}

void Stabile_process_init(Stabile__ctx_type_8 &_output_){
   Stabile__ctx_type_8_init(_output_);
   return ;
}

void Stabile_process(Stabile__ctx_type_8 &_ctx, float x, float cv, float q, _tuple___real_real_real__ &_output_){
   q = (q + 0.5f);
   uint8_t _cond_62;
   _cond_62 = (Util_change(_ctx._inst52,cv) || Util_change(_ctx._inst53,q));
   if(_cond_62){
      _ctx.g = Stabile_tune(cv);
      _ctx.R = (1.f / (2.f * (q + 1e-18f)));
      _ctx.inv_den = (1.f / (1.f + (2.f * _ctx.R * _ctx.g) + (_ctx.g * _ctx.g)));
   }
   float high;
   high = ((x + (- (((2.f * _ctx.R) + _ctx.g) * _ctx.z1)) + (- _ctx.z2)) * _ctx.inv_den);
   float band;
   band = ((_ctx.g * high) + _ctx.z1);
   float low;
   low = ((_ctx.g * band) + _ctx.z2);
   _ctx.z1 = ((_ctx.g * high) + band);
   _ctx.z2 = ((_ctx.g * band) + low);
   _tuple___real_real_real__ _tuple_63;
   {
      _tuple_63.field_0 = low;
      _tuple_63.field_1 = band;
      _tuple_63.field_2 = high;
   }
   _output_ = _tuple_63;
   return ;
}

void Stabile_default_init(Stabile__ctx_type_8 &_output_){
   Stabile__ctx_type_8_init(_output_);
   return ;
}

void Stabile_default(Stabile__ctx_type_8 &_ctx){
   _ctx.g = Stabile_calc_g(0.f,getSampleRate());
   _ctx.R = 1.f;
   _ctx.inv_den = (1.f / (1.f + (_ctx.g * _ctx.g)));
}

void Tricore__ctx_type_0_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0 _ctx;
   _ctx.reset_state = 0;
   _ctx.reset_phase = 0.f;
   _ctx.phase = 0.f;
   Util__ctx_type_1_init(_ctx._inst73);
   Util__ctx_type_1_init(_ctx._inst72);
   Util__ctx_type_16_init(_ctx._inst70);
   _output_ = _ctx;
   return ;
}

void Tricore_process_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

float Tricore_process(Tricore__ctx_type_0 &_ctx, float cv, float reset, float disable){
   _ctx.phase = (_ctx.phase + Util_cvToRate(_ctx._inst70,cv));
   uint8_t _cond_78;
   _cond_78 = (_ctx.phase > 1.f);
   if(_cond_78){
      _ctx.phase = (_ctx.phase + -1.f);
   }
   float sine_out;
   sine_out = Util_sine(_ctx.phase);
   uint8_t bdisable;
   bdisable = (disable > 0.5f);
   uint8_t _cond_79;
   _cond_79 = (Util_edge(_ctx._inst72,(reset > 0.f)) || Util_edge(_ctx._inst73,bdisable));
   if(_cond_79){
      _ctx.reset_phase = 1.f;
      _ctx.reset_state = 1;
   }
   float reset_out;
   reset_out = 1.f;
   if(_ctx.reset_state){
      uint8_t _cond_81;
      _cond_81 = ((fabsf(_ctx.reset_phase) > 0.001f) || bdisable);
      if(_cond_81){
         float reset_speed;
         if(bdisable){ reset_speed = 0.01f; }
         else
         { reset_speed = 0.5f; }
         _ctx.reset_phase = (_ctx.reset_phase + (- (_ctx.reset_phase * reset_speed)));
      }
      else
      {
         uint8_t _cond_80;
         _cond_80 = (_ctx.reset_phase > 0.001f);
         if(bool_not(_cond_80)){ _ctx.reset_phase = 0.f; }
         _ctx.reset_state = 0;
      }
      reset_out = _ctx.reset_phase;
   }
   return (sine_out * reset_out);
}

float Toh_tone_k1(float g){
   int index;
   index = int_clip(float_to_int((15.5f * (g + 1.f))),0,31);
   return (float_wrap_array(Toh_tone_k1_c0)[index] + (g * (float_wrap_array(Toh_tone_k1_c1)[index] + (float_wrap_array(Toh_tone_k1_c2)[index] * g))));
}

float Toh_tone_k0(float g){
   int index;
   index = int_clip(float_to_int((15.5f * (g + 1.f))),0,31);
   return (float_wrap_array(Toh_tone_k0_c0)[index] + (g * (float_wrap_array(Toh_tone_k0_c1)[index] + (float_wrap_array(Toh_tone_k0_c2)[index] * g))));
}

void Toh__ctx_type_2_init(Toh__ctx_type_2 &_output_){
   Toh__ctx_type_2 _ctx;
   _ctx.w1 = 0.f;
   _ctx.k1 = 0.f;
   _ctx.k0 = 0.f;
   _ctx.comp = 0.f;
   Util__ctx_type_2_init(_ctx._inst85);
   Toh_start(_ctx);
   _output_ = _ctx;
   return ;
}

void Toh_do_init(Toh__ctx_type_2 &_output_){
   Toh__ctx_type_2_init(_output_);
   return ;
}

float Toh_do(Toh__ctx_type_2 &_ctx, float x, float gain){
   uint8_t _cond_88;
   _cond_88 = Util_change(_ctx._inst85,gain);
   if(_cond_88){
      _ctx.k1 = Toh_tone_k1(gain);
      _ctx.k0 = Toh_tone_k0(gain);
      _ctx.comp = Util_map(fabsf(gain),0.f,1.f,1.f,1.8f);
   }
   float w0;
   w0 = (x + (- (_ctx.k0 * _ctx.w1)));
   float y0;
   y0 = ((_ctx.k0 * w0) + _ctx.w1);
   _ctx.w1 = w0;
   float sign;
   uint8_t _cond_89;
   _cond_89 = (gain < 0.f);
   if(_cond_89){ sign = -1.f; }
   else
   { sign = 1.f; }
   return (((_ctx.k1 * (x + (sign * y0)) * 0.5f) + x) * _ctx.comp);
}

void Toh_start_init(Toh__ctx_type_2 &_output_){
   Toh__ctx_type_2_init(_output_);
   return ;
}

void Toh_start(Toh__ctx_type_2 &_ctx){
   _ctx.k1 = 0.f;
   _ctx.k0 = -0.852723285867f;
   _ctx.comp = 1.f;
}

void Swept__ctx_type_0_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0 _ctx;
   _ctx.out = 0.f;
   Util__ctx_type_1_init(_ctx._inst91);
   _output_ = _ctx;
   return ;
}

void Swept_process_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0_init(_output_);
   return ;
}

float Swept_process(Swept__ctx_type_0 &_ctx, float gate, float start, float end, float rate){
   float a_rate;
   a_rate = (1.f / ((100.f * rate) + 0.01f));
   uint8_t bgate;
   bgate = (gate > 0.5f);
   _ctx.out = (_ctx.out + (((end * 1024.f) + (- _ctx.out)) * rate * 0.004f));
   uint8_t _cond_97;
   _cond_97 = Util_edge(_ctx._inst91,bgate);
   if(_cond_97){
      _ctx.out = (start * 1024.f);
   }
   return (_ctx.out * 0.0009765625f);
}

void Swept_noteOn_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0_init(_output_);
   return ;
}

void Swept_noteOn(Swept__ctx_type_0 &_ctx, int note, int velocity, int channel){
}

void Swept_noteOff_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0_init(_output_);
   return ;
}

void Swept_noteOff(Swept__ctx_type_0 &_ctx, int note, int channel){
}

void Swept_controlChange_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0_init(_output_);
   return ;
}

void Swept_controlChange(Swept__ctx_type_0 &_ctx, int control, int value, int channel){
}

void Swept_default_init(Swept__ctx_type_0 &_output_){
   Swept__ctx_type_0_init(_output_);
   return ;
}

void Swept_default(Swept__ctx_type_0 &_ctx){
}

void Noise__ctx_type_0_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0 _ctx;
   _ctx.x2 = 0;
   _ctx.x1 = 0;
   _output_ = _ctx;
   return ;
}

void Noise_process_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0_init(_output_);
   return ;
}

float Noise_process(Noise__ctx_type_0 &_ctx){
   _ctx.x1 = (((_ctx.x1 * 17389) + 7919) % 32768);
   float y1;
   y1 = (int_to_float(_ctx.x1) * 3.0517578125e-05f);
   _ctx.x2 = (((_ctx.x2 * 27449) + 12553) % 32768);
   float y2;
   y2 = (int_to_float(_ctx.x2) * 3.0517578125e-05f);
   float out;
   out = (y1 + (- y2));
   return (2.f * out);
}

void Noise_noteOn_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0_init(_output_);
   return ;
}

void Noise_noteOn(Noise__ctx_type_0 &_ctx, int note, int velocity, int channel){
}

void Noise_noteOff_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0_init(_output_);
   return ;
}

void Noise_noteOff(Noise__ctx_type_0 &_ctx, int note, int channel){
}

void Noise_controlChange_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0_init(_output_);
   return ;
}

void Noise_controlChange(Noise__ctx_type_0 &_ctx, int control, int value, int channel){
}

void Noise_default_init(Noise__ctx_type_0 &_output_){
   Noise__ctx_type_0_init(_output_);
   return ;
}

void Noise_default(Noise__ctx_type_0 &_ctx){
}

void Ahr__ctx_type_0_init(Ahr__ctx_type_0 &_output_){
   Ahr__ctx_type_0 _ctx;
   _ctx.target = 0.f;
   _ctx.state = 0;
   _ctx.rate = 0.f;
   _ctx.out = 0.f;
   _ctx.hold_phase = 0.f;
   Util__ctx_type_1_init(_ctx._inst106);
   Util__ctx_type_1_init(_ctx._inst104);
   _output_ = _ctx;
   return ;
}

void Ahr_do_init(Ahr__ctx_type_0 &_output_){
   Ahr__ctx_type_0_init(_output_);
   return ;
}

void Ahr_do(Ahr__ctx_type_0 &_ctx, float gate, float a, float h, float r, _tuple___real_real__ &_output_){
   int release;
   release = 0;
   int attack;
   attack = 1;
   int hold;
   hold = 2;
   int reset;
   reset = 3;
   uint8_t bgate;
   bgate = (gate > 0.f);
   uint8_t _cond_123;
   _cond_123 = Util_edge(_ctx._inst104,bgate);
   if(_cond_123){
      _ctx.state = reset;
   }
   float resetting;
   uint8_t _cond_132;
   _cond_132 = (_ctx.state == reset);
   if(_cond_132){ resetting = 1.f; }
   else
   { resetting = 0.f; }
   uint8_t _cond_124;
   _cond_124 = Util_edge(_ctx._inst106,(_ctx.out > 1024.f));
   if(_cond_124){
      _ctx.hold_phase = 0.f;
      _ctx.state = hold;
   }
   uint8_t _cond_125;
   _cond_125 = ((_ctx.out < 10.f) && (_ctx.state == reset));
   if(_cond_125){
      _ctx.state = attack;
   }
   uint8_t _cond_126;
   _cond_126 = ((_ctx.hold_phase > 100.f) && (_ctx.state == hold));
   if(_cond_126){
      _ctx.state = release;
   }
   uint8_t _cond_127;
   _cond_127 = (_ctx.state == reset);
   if(_cond_127){
      _ctx.rate = 0.952380952381f;
      _ctx.target = 0.f;
   }
   uint8_t _cond_128;
   _cond_128 = (_ctx.state == attack);
   if(_cond_128){
      _ctx.rate = (1.f / ((100.f * a) + 0.05f));
      _ctx.target = 1228.8f;
   }
   uint8_t _cond_129;
   _cond_129 = (_ctx.state == hold);
   if(_cond_129){
      float hrate;
      hrate = (1.f / ((100.f * h) + 0.05f));
      _ctx.hold_phase = (_ctx.hold_phase + hrate);
   }
   uint8_t _cond_130;
   _cond_130 = (_ctx.state == release);
   if(_cond_130){
      _ctx.rate = (1.f / ((200.f * r) + 0.05f));
      _ctx.target = 0.f;
   }
   _ctx.out = (_ctx.out + ((_ctx.target + (- _ctx.out)) * _ctx.rate * 0.005f));
   _tuple___real_real__ _tuple_131;
   {
      _tuple_131.field_0 = float_clip((_ctx.out * 0.0009765625f),0.f,1.f);
      _tuple_131.field_1 = resetting;
   }
   _output_ = _tuple_131;
   return ;
}

void Ahr__ctx_type_1_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1 _ctx;
   _ctx.knob3 = 0.f;
   _ctx.knob2 = 0.f;
   _ctx.knob1 = 0.f;
   Ahr__ctx_type_0_init(_ctx._inst115);
   _output_ = _ctx;
   return ;
}

void Ahr_process_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1_init(_output_);
   return ;
}

void Ahr_process(Ahr__ctx_type_1 &_ctx, float gate, _tuple___real_real__ &_output_){
   _tuple___real_real__ _call_134;
   Ahr_do(_ctx._inst115,gate,_ctx.knob1,_ctx.knob2,_ctx.knob3,_call_134);
   _output_ = _call_134;
   return ;
}

void Ahr_noteOn_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1_init(_output_);
   return ;
}

void Ahr_noteOn(Ahr__ctx_type_1 &_ctx, int note, int velocity, int channel){
}

void Ahr_noteOff_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1_init(_output_);
   return ;
}

void Ahr_noteOff(Ahr__ctx_type_1 &_ctx, int note, int channel){
}

void Ahr_controlChange_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1_init(_output_);
   return ;
}

void Ahr_controlChange(Ahr__ctx_type_1 &_ctx, int control, int value, int channel){
   uint8_t _cond_136;
   _cond_136 = (control == 1);
   if(_cond_136){
      _ctx.knob1 = (int_to_float(value) * 0.00787401574803f);
   }
   uint8_t _cond_137;
   _cond_137 = (control == 2);
   if(_cond_137){
      _ctx.knob2 = (int_to_float(value) * 0.00787401574803f);
   }
   uint8_t _cond_138;
   _cond_138 = (control == 3);
   if(_cond_138){
      _ctx.knob3 = (int_to_float(value) * 0.00787401574803f);
   }
}

void Ahr_default_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1_init(_output_);
   return ;
}

void Ahr_default(Ahr__ctx_type_1 &_ctx){
   _ctx.knob1 = 0.f;
   _ctx.knob2 = 0.5f;
   _ctx.knob3 = 0.5f;
}

void Trummor__ctx_type_0_init(Trummor__ctx_type_0 &_output_){
   Trummor__ctx_type_0 _ctx;
   _ctx.tone = 0.f;
   _ctx.pitch = 0.f;
   _ctx.level2 = 0.f;
   _ctx.level1 = 0.f;
   _ctx.int_osc = 0.f;
   _ctx.int_noise = 0.f;
   _ctx.ext_osc = 0.f;
   _ctx.ext_noise = 0.f;
   _ctx.env2_r = 0.f;
   _ctx.env2_h = 0.f;
   _ctx.env2_a = 0.f;
   _ctx.env1_r = 0.f;
   _ctx.env1_h = 0.f;
   _ctx.env1_a = 0.f;
   _ctx.drive = 0.f;
   _ctx.bend = 0.f;
   Toh__ctx_type_2_init(_ctx._inst153);
   Noise__ctx_type_0_init(_ctx._inst152);
   Ahr__ctx_type_0_init(_ctx._inst151);
   Tricore__ctx_type_0_init(_ctx._inst150);
   Swept__ctx_type_0_init(_ctx._inst149);
   Ahr__ctx_type_0_init(_ctx._inst148);
   _output_ = _ctx;
   return ;
}

void Trummor_do_init(Trummor__ctx_type_0 &_output_){
   Trummor__ctx_type_0_init(_output_);
   return ;
}

void Trummor_do(Trummor__ctx_type_0 &_ctx, float gate, float osc_in, float noise_in, _tuple___real_real_real_real__ &_output_){
   float osc_env;
   float env_reset;
   _tuple___real_real__ _call_182;
   Ahr_do(_ctx._inst148,gate,_ctx.env1_a,_ctx.env1_h,_ctx.env1_r,_call_182);
   osc_env = _call_182.field_0;env_reset = _call_182.field_1;
   float cv;
   cv = Swept_process(_ctx._inst149,(1.f + (- env_reset)),(_ctx.pitch + (_ctx.bend * 0.4f)),_ctx.pitch,0.1f);
   float osc;
   osc = ((_ctx.int_osc * Tricore_process(_ctx._inst150,cv,0.f,env_reset)) + (_ctx.ext_osc * osc_in));
   float osc_sat;
   osc_sat = Util_saturate(((_ctx.drive + 1.f) * osc));
   float noise_env;
   _tuple___real_real__ _call_183;
   Ahr_do(_ctx._inst151,gate,_ctx.env2_a,_ctx.env2_h,_ctx.env2_r,_call_183);
   noise_env = _call_183.field_0;
   float noise_osc;
   noise_osc = Toh_do(_ctx._inst153,((_ctx.int_noise * Noise_process(_ctx._inst152)) + (_ctx.ext_noise * noise_in)),_ctx.tone);
   float output;
   output = ((_ctx.level1 * osc_env * osc_sat) + (_ctx.level2 * noise_env * noise_osc));
   _tuple___real_real_real_real__ _tuple_184;
   {
      _tuple_184.field_0 = output;
      _tuple_184.field_1 = cv;
      _tuple_184.field_2 = osc_env;
      _tuple_184.field_3 = noise_env;
   }
   _output_ = _tuple_184;
   return ;
}

void Trummor_setParameter_init(Trummor__ctx_type_0 &_output_){
   Trummor__ctx_type_0_init(_output_);
   return ;
}

void Trummor_setParameter(Trummor__ctx_type_0 &_ctx, int param, float value){
   uint8_t _cond_205;
   _cond_205 = (param == 0);
   if(_cond_205){
      _ctx.level1 = value;
   }
   else
   {
      uint8_t _cond_204;
      _cond_204 = (param == 1);
      if(_cond_204){
         _ctx.level2 = value;
      }
      else
      {
         uint8_t _cond_203;
         _cond_203 = (param == 2);
         if(_cond_203){
            _ctx.env1_a = value;
         }
         else
         {
            uint8_t _cond_202;
            _cond_202 = (param == 3);
            if(_cond_202){
               _ctx.env1_h = value;
            }
            else
            {
               uint8_t _cond_201;
               _cond_201 = (param == 4);
               if(_cond_201){
                  _ctx.env1_r = value;
               }
               else
               {
                  uint8_t _cond_200;
                  _cond_200 = (param == 5);
                  if(_cond_200){
                     _ctx.env2_a = value;
                  }
                  else
                  {
                     uint8_t _cond_199;
                     _cond_199 = (param == 6);
                     if(_cond_199){
                        _ctx.env2_h = value;
                     }
                     else
                     {
                        uint8_t _cond_198;
                        _cond_198 = (param == 7);
                        if(_cond_198){
                           _ctx.env2_r = value;
                        }
                        else
                        {
                           uint8_t _cond_197;
                           _cond_197 = (param == 8);
                           if(_cond_197){
                              _ctx.pitch = value;
                           }
                           else
                           {
                              uint8_t _cond_196;
                              _cond_196 = (param == 9);
                              if(_cond_196){
                                 _ctx.bend = value;
                              }
                              else
                              {
                                 uint8_t _cond_195;
                                 _cond_195 = (param == 10);
                                 if(_cond_195){
                                    _ctx.drive = value;
                                 }
                                 else
                                 {
                                    uint8_t _cond_194;
                                    _cond_194 = (param == 11);
                                    if(_cond_194){
                                       _ctx.tone = value;
                                    }
                                    else
                                    {
                                       uint8_t _cond_193;
                                       _cond_193 = (param == 12);
                                       if(_cond_193){
                                          uint8_t _cond_188;
                                          _cond_188 = ((value == 0.f) || (value == 1.f));
                                          if(_cond_188){ _ctx.int_osc = 1.f; }
                                          else
                                          { _ctx.int_osc = 0.f; }
                                          uint8_t _cond_189;
                                          _cond_189 = ((value == 1.f) || (value == 2.f));
                                          if(_cond_189){ _ctx.ext_osc = 1.f; }
                                          else
                                          { _ctx.ext_osc = 0.f; }
                                       }
                                       else
                                       {
                                          uint8_t _cond_192;
                                          _cond_192 = (param == 13);
                                          if(_cond_192){
                                             uint8_t _cond_190;
                                             _cond_190 = ((value == 0.f) || (value == 1.f));
                                             if(_cond_190){ _ctx.int_noise = 1.f; }
                                             else
                                             { _ctx.int_noise = 0.f; }
                                             uint8_t _cond_191;
                                             _cond_191 = ((value == 1.f) || (value == 2.f));
                                             if(_cond_191){ _ctx.ext_noise = 1.f; }
                                             else
                                             { _ctx.ext_noise = 0.f; }
                                          }
                                       }
                                    }
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

void Rescomb__ctx_type_0_init(Rescomb__ctx_type_0 &_output_){
   Rescomb__ctx_type_0 _ctx;
   _ctx.write_pos = 0;
   float_init_array(3000,0.f,_ctx.buffer);
   _output_ = _ctx;
   return ;
}

void Rescomb_delay_init(Rescomb__ctx_type_0 &_output_){
   Rescomb__ctx_type_0_init(_output_);
   return ;
}

float Rescomb_delay(Rescomb__ctx_type_0 &_ctx, float x, float cv){
   _ctx.write_pos = ((_ctx.write_pos + 1) % 3000);
   float_set(_ctx.buffer,_ctx.write_pos,x);
   float r_size;
   r_size = 3000.f;
   float r_index;
   r_index = fmodf((int_to_float(_ctx.write_pos) + (- (Util_cvToperiodUnit(cv) * getSampleRate()))),r_size);
   uint8_t _cond_219;
   _cond_219 = (r_index < 0.f);
   if(_cond_219){ r_index = (r_size + r_index); }
   int t1;
   t1 = (float_to_int(floorf(r_index)) % 3000);
   int t2;
   t2 = ((t1 + 1) % 3000);
   float decimal;
   decimal = (r_index + (- int_to_float(t1)));
   float x1;
   x1 = float_get(_ctx.buffer,t1);
   float x2;
   x2 = float_get(_ctx.buffer,t2);
   float ret;
   ret = (((x2 + (- x1)) * decimal) + x1);
   return ret;
}

float Rescomb_toneCurve(float tone){
   int index;
   index = int_clip(float_to_int((26.25f * (tone + 1.2f))),0,63);
   return (float_wrap_array(Rescomb_toneCurve_c0)[index] + (tone * (float_wrap_array(Rescomb_toneCurve_c1)[index] + (float_wrap_array(Rescomb_toneCurve_c2)[index] * tone))));
}

void Rescomb__ctx_type_2_init(Rescomb__ctx_type_2 &_output_){
   Rescomb__ctx_type_2 _ctx;
   _ctx.stone = 0.f;
   _ctx.output = 0.f;
   Rescomb__ctx_type_0_init(_ctx._inst218);
   Util__ctx_type_8_init(_ctx._inst217);
   Util__ctx_type_2_init(_ctx._inst215);
   _output_ = _ctx;
   return ;
}

void Rescomb_do_init(Rescomb__ctx_type_2 &_output_){
   Rescomb__ctx_type_2_init(_output_);
   return ;
}

float Rescomb_do(Rescomb__ctx_type_2 &_ctx, float in, float cv, float tone, float res){
   uint8_t _cond_221;
   _cond_221 = Util_change(_ctx._inst215,tone);
   if(_cond_221){
      _ctx.stone = Rescomb_toneCurve(tone);
   }
   float feedback;
   feedback = Util_dcblock(_ctx._inst217,(_ctx.output * res));
   float saturated_input;
   saturated_input = Util_stanh((in + feedback));
   _ctx.output = ((_ctx.stone * Rescomb_delay(_ctx._inst218,saturated_input,cv)) + in);
   return Util_stanh(_ctx.output);
}

float Lateralus_tune(float cut, float fs, float oversampling){
   float f;
   f = Util_cvTokHz(cut);
   f = float_clip(f,0.f,20.f);
   float fh;
   fh = ((6.28318530718f * f) / (oversampling * fs));
   return fh;
}

float Lateralus_tune_44100(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_44100_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_44100_c1)[index] + (float_wrap_array(Lateralus_tune_44100_c2)[index] * cut))));
}

float Lateralus_tune_48000(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_48000_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_48000_c1)[index] + (float_wrap_array(Lateralus_tune_48000_c2)[index] * cut))));
}

float Lateralus_tune_88200(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_88200_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_88200_c1)[index] + (float_wrap_array(Lateralus_tune_88200_c2)[index] * cut))));
}

float Lateralus_tune_96000(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_96000_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_96000_c1)[index] + (float_wrap_array(Lateralus_tune_96000_c2)[index] * cut))));
}

float Lateralus_tune_176400(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_176400_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_176400_c1)[index] + (float_wrap_array(Lateralus_tune_176400_c2)[index] * cut))));
}

float Lateralus_tune_192000(float cut){
   int index;
   index = int_clip(float_to_int((127.f * cut)),0,127);
   return (float_wrap_array(Lateralus_tune_192000_c0)[index] + (cut * (float_wrap_array(Lateralus_tune_192000_c1)[index] + (float_wrap_array(Lateralus_tune_192000_c2)[index] * cut))));
}

float Lateralus_getTune(float cut, float fs){
   uint8_t _cond_258;
   _cond_258 = (fs == 44100.f);
   if(_cond_258){
      return Lateralus_tune_44100(cut);
   }
   else
   {
      uint8_t _cond_257;
      _cond_257 = (fs == 48000.f);
      if(_cond_257){
         return Lateralus_tune_48000(cut);
      }
      else
      {
         uint8_t _cond_256;
         _cond_256 = (fs == 88200.f);
         if(_cond_256){
            return Lateralus_tune_88200(cut);
         }
         else
         {
            uint8_t _cond_255;
            _cond_255 = (fs == 96000.f);
            if(_cond_255){
               return Lateralus_tune_96000(cut);
            }
            else
            {
               uint8_t _cond_254;
               _cond_254 = (fs == 176400.f);
               if(_cond_254){
                  return Lateralus_tune_176400(cut);
               }
               else
               {
                  uint8_t _cond_253;
                  _cond_253 = (fs == 192000.f);
                  if(_cond_253){
                     return Lateralus_tune_192000(cut);
                  }
                  else
                  {
                     return Lateralus_tune(cut,fs,4.f);
                  }
               }
            }
         }
      }
   }
}

void Lateralus__ctx_type_8_init(Lateralus__ctx_type_8 &_output_){
   Lateralus__ctx_type_8 _ctx;
   _ctx.p3 = 0.f;
   _ctx.p2 = 0.f;
   _ctx.p1 = 0.f;
   _ctx.p0 = 0.f;
   _output_ = _ctx;
   return ;
}

void Lateralus_heun_init(Lateralus__ctx_type_8 &_output_){
   Lateralus__ctx_type_8_init(_output_);
   return ;
}

void Lateralus_heun(Lateralus__ctx_type_8 &_ctx, float input, float fh, float res, _tuple___real_real__ &_output_){
   float wt0;
   wt0 = Util_cubic_clipper((input + (-4.f * res * _ctx.p3)));
   float wt1;
   wt1 = Util_cubic_clipper(_ctx.p0);
   float dpt0;
   dpt0 = ((wt0 + (- wt1)) * fh);
   float wt3;
   wt3 = Util_cubic_clipper(_ctx.p1);
   float dpt1;
   dpt1 = ((wt1 + (- wt3)) * fh);
   float wt5;
   wt5 = Util_cubic_clipper(_ctx.p2);
   float dpt2;
   dpt2 = ((wt3 + (- wt5)) * fh);
   float wt7;
   wt7 = Util_cubic_clipper(_ctx.p3);
   float dpt3;
   dpt3 = ((wt5 + (- wt7)) * fh);
   float pt0;
   pt0 = (_ctx.p0 + dpt0);
   float pt1;
   pt1 = (_ctx.p1 + dpt1);
   float pt2;
   pt2 = (_ctx.p2 + dpt2);
   float pt3;
   pt3 = (_ctx.p3 + dpt3);
   float w0;
   w0 = Util_cubic_clipper((input + (-4.f * res * pt3)));
   float w1;
   w1 = Util_cubic_clipper(pt0);
   float dp0;
   dp0 = ((w0 + (- w1)) * fh);
   float w3;
   w3 = Util_cubic_clipper(pt1);
   float dp1;
   dp1 = ((w1 + (- w3)) * fh);
   float w5;
   w5 = Util_cubic_clipper(pt2);
   float dp2;
   dp2 = ((w3 + (- w5)) * fh);
   float w7;
   w7 = Util_cubic_clipper(pt3);
   float dp3;
   dp3 = ((w5 + (- w7)) * fh);
   _ctx.p0 = (_ctx.p0 + ((dp0 + dpt0) * 0.5f));
   _ctx.p1 = (_ctx.p1 + ((dp1 + dpt1) * 0.5f));
   _ctx.p2 = (_ctx.p2 + ((dp2 + dpt2) * 0.5f));
   _ctx.p3 = (_ctx.p3 + ((dp3 + dpt3) * 0.5f));
   _tuple___real_real__ _tuple_259;
   {
      _tuple_259.field_0 = _ctx.p1;
      _tuple_259.field_1 = _ctx.p3;
   }
   _output_ = _tuple_259;
   return ;
}

void Lateralus__ctx_type_9_init(Lateralus__ctx_type_9 &_output_){
   Lateralus__ctx_type_9 _ctx;
   Lateralus__ctx_type_8_init(_ctx.h);
   _ctx.fh = 0.f;
   Util__ctx_type_2_init(_ctx._inst245);
   Util__ctx_type_2_init(_ctx._inst244);
   _output_ = _ctx;
   return ;
}

void Lateralus_process_heun_init(Lateralus__ctx_type_9 &_output_){
   Lateralus__ctx_type_9_init(_output_);
   return ;
}

void Lateralus_process_heun(Lateralus__ctx_type_9 &_ctx, float input, float cut, float res, _tuple___real_real__ &_output_){
   float fs;
   fs = getSampleRate();
   uint8_t _cond_261;
   _cond_261 = (Util_change(_ctx._inst244,cut) || Util_change(_ctx._inst245,fs));
   if(_cond_261){
      _ctx.fh = Lateralus_getTune(cut,fs);
   }
   float db12;
   float db24;
   db12 = 0.f;
   db24 = 0.f;
   uint8_t _cond_278;
   _cond_278 = ((fs == 176400.f) || (fs == 192000.f));
   if(_cond_278){
      _tuple___real_real__ _call_263;
      Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_263);
      db12 = _call_263.field_0;db24 = _call_263.field_1;
   }
   else
   {
      uint8_t _cond_277;
      _cond_277 = ((fs == 88200.f) || (fs == 96000.f));
      if(_cond_277){
         _tuple___real_real__ _call_265;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_265);
         db12 = _call_265.field_0;db24 = _call_265.field_1;
         _tuple___real_real__ _call_266;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_266);
         db12 = _call_266.field_0;db24 = _call_266.field_1;
      }
      else
      {
         _tuple___real_real__ _call_269;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_269);
         db12 = _call_269.field_0;db24 = _call_269.field_1;
         _tuple___real_real__ _call_270;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_270);
         db12 = _call_270.field_0;db24 = _call_270.field_1;
         _tuple___real_real__ _call_271;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_271);
         db12 = _call_271.field_0;db24 = _call_271.field_1;
         _tuple___real_real__ _call_272;
         Lateralus_heun(_ctx.h,input,_ctx.fh,res,_call_272);
         db12 = _call_272.field_0;db24 = _call_272.field_1;
      }
   }
   _tuple___real_real__ _tuple_279;
   {
      _tuple_279.field_0 = (db12 * (1.f + (res * 0.5f)));
      _tuple_279.field_1 = (db24 * (1.f + res));
   }
   _output_ = _tuple_279;
   return ;
}

void Lateralus__ctx_type_10_init(Lateralus__ctx_type_10 &_output_){
   Lateralus__ctx_type_10 _ctx;
   Lateralus__ctx_type_9_init(_ctx._inst252);
   _output_ = _ctx;
   return ;
}

void Lateralus_process_init(Lateralus__ctx_type_10 &_output_){
   Lateralus__ctx_type_10_init(_output_);
   return ;
}

void Lateralus_process(Lateralus__ctx_type_10 &_ctx, float input, float cut, float res, _tuple___real_real__ &_output_){
   _tuple___real_real__ _call_281;
   Lateralus_process_heun(_ctx._inst252,(input + 1e-05f),cut,res,_call_281);
   _output_ = _call_281;
   return ;
}

float Debriatus_saturate(float x){
   int index;
   index = int_clip(float_to_int((5.f * (x + 24.f))),0,240);
   return (float_wrap_array(Debriatus_saturate_c0)[index] + (x * (float_wrap_array(Debriatus_saturate_c1)[index] + (float_wrap_array(Debriatus_saturate_c2)[index] * x))));
}

float Debriatus_factor(float cv){
   int index;
   index = int_clip(float_to_int((127.f * cv)),0,127);
   return (float_wrap_array(Debriatus_factor_c0)[index] + (cv * (float_wrap_array(Debriatus_factor_c1)[index] + (float_wrap_array(Debriatus_factor_c2)[index] * cv))));
}

float Debriatus_crush(float i, float cv){
   float out;
   out = i;
   uint8_t _cond_350;
   _cond_350 = (cv == 0.f);
   if(_cond_350){
      out = i;
   }
   else
   {
      float b;
      b = Debriatus_factor(cv);
      int x;
      x = float_to_int((i * b));
      out = (int_to_float(x) / b);
   }
   return out;
}

float Debriatus_fold(float signal, float level){
   float sign;
   uint8_t _cond_351;
   _cond_351 = (signal > 0.f);
   if(_cond_351){ sign = 1.f; }
   else
   { sign = -1.f; }
   float amp;
   amp = (fabsf(signal) * ((8.f * level) + 1.f));
   float base;
   base = floorf(amp);
   float delta;
   delta = (amp + (- base));
   float out;
   uint8_t _cond_352;
   _cond_352 = ((float_to_int(base) % 2) != 0);
   if(_cond_352){ out = (1.f + (- delta)); }
   else
   { out = delta; }
   return (sign * out);
}

float Debriatus_process(float input, float fold, float crush, float distort, float saturate){
   float x;
   x = Debriatus_fold(input,fold);
   float y;
   y = Debriatus_crush(x,crush);
   float z;
   z = ((y * (1.f + (-2.f * distort))) + (y * y * y * distort * 8.f) + (- distort));
   float out;
   out = Debriatus_saturate((z * (1.f + (saturate * 8.f))));
   return out;
}

void VultEngine__ctx_type_0_init(VultEngine__ctx_type_0 &_output_){
   VultEngine__ctx_type_0 _ctx;
   Rescomb__ctx_type_2_init(_ctx.inst);
   _output_ = _ctx;
   return ;
}

void VultEngine_rescomb_init(VultEngine__ctx_type_0 &_output_){
   VultEngine__ctx_type_0_init(_output_);
   return ;
}

float VultEngine_rescomb(VultEngine__ctx_type_0 &_ctx, float in, float cv_in, float tone_in, float res_in){
   float i;
   i = float_clip(in,-10.f,10.f);
   float cv;
   cv = float_clip(cv_in,0.f,1.f);
   float tone;
   tone = float_clip(tone_in,-1.05f,1.05f);
   float res;
   res = float_clip(res_in,-1.1f,1.1f);
   return Rescomb_do(_ctx.inst,i,cv,tone,res);
}

void VultEngine__ctx_type_1_init(VultEngine__ctx_type_1 &_output_){
   VultEngine__ctx_type_1 _ctx;
   Stabile__ctx_type_8_init(_ctx._inst355);
   _output_ = _ctx;
   return ;
}

void VultEngine_stabile_init(VultEngine__ctx_type_1 &_output_){
   VultEngine__ctx_type_1_init(_output_);
   return ;
}

void VultEngine_stabile(VultEngine__ctx_type_1 &_ctx, float in, float cut_in, float res_in, _tuple___real_real_real__ &_output_){
   float cut;
   cut = float_clip(cut_in,0.f,0.92f);
   float res;
   res = float_clip(res_in,0.f,4.f);
   _tuple___real_real_real__ _call_361;
   Stabile_process(_ctx._inst355,in,cut,res,_call_361);
   _output_ = _call_361;
   return ;
}

void VultEngine__ctx_type_2_init(VultEngine__ctx_type_2 &_output_){
   VultEngine__ctx_type_2 _ctx;
   Lateralus__ctx_type_10_init(_ctx._inst357);
   _output_ = _ctx;
   return ;
}

void VultEngine_lateralus_init(VultEngine__ctx_type_2 &_output_){
   VultEngine__ctx_type_2_init(_output_);
   return ;
}

void VultEngine_lateralus(VultEngine__ctx_type_2 &_ctx, float in, float cut_in, float res_in, _tuple___real_real__ &_output_){
   float cut;
   cut = float_clip(cut_in,0.f,1.f);
   float res;
   res = float_clip(res_in,0.f,1.f);
   _tuple___real_real__ _call_363;
   Lateralus_process(_ctx._inst357,in,cut,res,_call_363);
   _output_ = _call_363;
   return ;
}

float VultEngine_debriatus(float in, float fold_in, float crush_in, float distort_in, float saturate_in){
   float fold;
   fold = float_clip(fold_in,0.f,1.f);
   float crush;
   crush = float_clip(crush_in,0.f,1.f);
   float distort;
   distort = float_clip(distort_in,0.f,1.f);
   float saturate;
   saturate = float_clip(saturate_in,0.f,1.f);
   return Debriatus_process(in,fold,crush,distort,saturate);
}

void VultEngine__ctx_type_4_init(VultEngine__ctx_type_4 &_output_){
   VultEngine__ctx_type_4 _ctx;
   Trummor__ctx_type_0_init(_ctx.processor);
   _output_ = _ctx;
   return ;
}

void VultEngine_trummor_init(VultEngine__ctx_type_4 &_output_){
   VultEngine__ctx_type_4_init(_output_);
   return ;
}

void VultEngine_trummor(VultEngine__ctx_type_4 &_ctx, float gate, float osc_in, float noise_in, _tuple___real_real_real_real__ &_output_){
   _tuple___real_real_real_real__ _call_365;
   Trummor_do(_ctx.processor,gate,osc_in,noise_in,_call_365);
   _output_ = _call_365;
   return ;
}

void VultEngine_trummor_param_init(VultEngine__ctx_type_4 &_output_){
   VultEngine__ctx_type_4_init(_output_);
   return ;
}

void VultEngine_trummor_param(VultEngine__ctx_type_4 &_ctx, int param, float value){
   Trummor_setParameter(_ctx.processor,param,value);
}


